# -*- coding: utf-8 -*-
"""Test wizard functionality with user-friendly token format"""

import re
from odoo.tests.common import TransactionCase


class TestSetupTokenWizardUserFriendly(TransactionCase):
    """Test suite for setup token wizard with new user-friendly format"""

    def setUp(self):
        super().setUp()
        # Create test host
        self.host_obj = self.env['sunray.host'].create({
            'domain': 'wizard-test.example.com',
            'backend_url': 'http://localhost:8000'
        })
        
        # Create test user
        self.user_obj = self.env['sunray.user'].create({
            'username': 'wizarduser',
            'email': 'wizard@example.com',
            'is_active': True
        })
    
    def test_01_wizard_generates_user_friendly_format(self):
        """Test that wizard generates tokens in user-friendly format"""
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'Wizard Test Device',
            'validity_hours': 24,
            'max_uses': 1
        })
        
        # Generate token
        result = wizard.generate_token()
        
        # Verify token is generated
        self.assertTrue(wizard.generated_token)
        
        # Verify format: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
        self.assertRegex(
            wizard.generated_token, 
            r'^[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}$'
        )
        
        # Verify length
        self.assertEqual(len(wizard.generated_token), 29)  # 25 chars + 4 dashes
        
        # Verify no ambiguous characters
        for bad_char in ['0', 'O', 'I', 'L', '1']:
            self.assertNotIn(bad_char, wizard.generated_token)
    
    def test_02_wizard_display_instructions(self):
        """Test that wizard displays proper instructions for new format"""
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'Display Test Device',
            'validity_hours': 48,
            'max_uses': 2,
            'allowed_cidrs': '192.168.1.0/24'
        })
        
        # Generate token
        wizard.generate_token()
        
        # Verify display content
        self.assertTrue(wizard.token_display)
        
        # Check for key elements in display
        expected_elements = [
            '🔑 TOKEN:',
            wizard.generated_token,
            '👤 Username: wizarduser',
            '🌐 Host: wizard-test.example.com',
            '📱 Device: Display Test Device',
            '🔢 Max Uses: 2',
            'Groups of 5 characters separated by dashes for easy dictation',
            'Token expires in 48 hours',
            'Can be used 2 time(s)',
            'IP restriction: 192.168.1.0/24'
        ]
        
        for element in expected_elements:
            self.assertIn(element, wizard.token_display)
    
    def test_03_wizard_action_returns_correct_format(self):
        """Test that wizard action returns correct Odoo action format"""
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'Action Test Device'
        })
        
        # Generate token and get action
        action = wizard.generate_token()
        
        # Verify action structure
        self.assertEqual(action['type'], 'ir.actions.act_window')
        self.assertEqual(action['res_model'], 'sunray.setup.token.wizard')
        self.assertEqual(action['view_mode'], 'form')
        self.assertEqual(action['res_id'], wizard.id)
        self.assertEqual(action['target'], 'new')
        self.assertIn('context', action)
    
    def test_04_wizard_token_validation_works(self):
        """Test that tokens generated by wizard can be validated successfully"""
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'Validation Test Device',
            'validity_hours': 24,
            'allowed_cidrs': '10.0.0.0/8'
        })
        
        # Generate token
        wizard.generate_token()
        
        # Test validation with the generated token
        result = self.env['sunray.setup.token'].validate_setup_token(
            username='wizarduser',
            token_hash=wizard.generated_token,
            host_domain='wizard-test.example.com',
            client_ip='10.1.1.100',  # Within allowed CIDR
            worker_id='test-worker'
        )
        
        # Verify validation succeeds
        self.assertTrue(result['valid'])
        self.assertEqual(result['user_obj'], self.user_obj)
        self.assertEqual(result['host_obj'], self.host_obj)
        self.assertIsNone(result['error_code'])
        self.assertIsNone(result['error_message'])
        
        # Test validation with disallowed IP
        blocked_result = self.env['sunray.setup.token'].validate_setup_token(
            username='wizarduser',
            token_hash=wizard.generated_token,
            host_domain='wizard-test.example.com',
            client_ip='192.168.1.100',  # Outside allowed CIDR
            worker_id='test-worker'
        )
        
        # Verify validation fails for wrong IP
        self.assertFalse(blocked_result['valid'])
        self.assertEqual(blocked_result['error_code'], '403')
    
    def test_05_wizard_commits_transaction(self):
        """Test that wizard properly commits the transaction"""
        # Count tokens before
        initial_count = self.env['sunray.setup.token'].search_count([])
        
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'Commit Test Device'
        })
        
        # Generate token (should commit)
        wizard.generate_token()
        
        # Verify token was created and committed
        final_count = self.env['sunray.setup.token'].search_count([])
        self.assertEqual(final_count, initial_count + 1)
        
        # Find the created token
        created_token = self.env['sunray.setup.token'].search([
            ('device_name', '=', 'Commit Test Device')
        ])
        self.assertTrue(created_token)
        
        # Verify it can be validated immediately (proving it's committed)
        result = self.env['sunray.setup.token'].validate_setup_token(
            username='wizarduser',
            token_hash=wizard.generated_token,
            host_domain='wizard-test.example.com'
        )
        self.assertTrue(result['valid'])
    
    def test_06_wizard_handles_special_characters_in_cidrs(self):
        """Test that wizard handles CIDR comments and special formatting"""
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'CIDR Test Device',
            'allowed_cidrs': """# Office network
192.168.1.0/24    # Main office
10.0.0.0/8        # VPN network
# 172.16.0.0/12   # Commented out network
"""
        })
        
        # Generate token
        wizard.generate_token()
        
        # Verify CIDR information appears in display
        self.assertIn('IP restriction: 192.168.1.0/24, 10.0.0.0/8', wizard.token_display)
        
        # Verify token validation respects parsed CIDRs
        # Should work with office network
        office_result = self.env['sunray.setup.token'].validate_setup_token(
            username='wizarduser',
            token_hash=wizard.generated_token,
            host_domain='wizard-test.example.com',
            client_ip='192.168.1.100'
        )
        self.assertTrue(office_result['valid'])
        
        # Should work with VPN network
        vpn_result = self.env['sunray.setup.token'].validate_setup_token(
            username='wizarduser',
            token_hash=wizard.generated_token,
            host_domain='wizard-test.example.com',
            client_ip='10.1.1.100'
        )
        self.assertTrue(vpn_result['valid'])
        
        # Should fail with commented out network
        blocked_result = self.env['sunray.setup.token'].validate_setup_token(
            username='wizarduser',
            token_hash=wizard.generated_token,
            host_domain='wizard-test.example.com',
            client_ip='172.16.1.100'
        )
        self.assertFalse(blocked_result['valid'])
    
    def test_07_wizard_multi_use_tokens(self):
        """Test wizard with multi-use tokens"""
        wizard = self.env['sunray.setup.token.wizard'].create({
            'user_id': self.user_obj.id,
            'host_id': self.host_obj.id,
            'device_name': 'Multi-Use Test Device',
            'max_uses': 5
        })
        
        # Generate token
        wizard.generate_token()
        
        # Find the created token
        token_obj = self.env['sunray.setup.token'].search([
            ('device_name', '=', 'Multi-Use Test Device')
        ])
        self.assertTrue(token_obj)
        self.assertEqual(token_obj.max_uses, 5)
        self.assertEqual(token_obj.current_uses, 0)
        self.assertFalse(token_obj.consumed)
        
        # Verify display shows correct max uses
        self.assertIn('Can be used 5 time(s)', wizard.token_display)
        
        # Test consumption workflow
        for i in range(1, 6):
            result = token_obj.consume()
            self.assertEqual(result['current_uses'], i)
            self.assertEqual(result['consumed'], i >= 5)
        
        # After 5 uses, should be consumed
        self.assertTrue(token_obj.consumed)